AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Security/Eval:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'spec/*/*spec.rb'


