require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Security/Eval:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/*/*spec.rb'
